# Generated by Django 3.2.25 on 2024-08-19 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_alter_problem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(db_index=True, help_text='The full name of the problem, as shown in the problem list.', max_length=50, validators=[django.core.validators.RegexValidator('^[^/]*$', 'Problem name must be ^[^/]*$')], verbose_name='problem name'),
        ),
    ]
