# Generated by Django 3.2.25 on 2024-08-27 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_alter_problem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '과목',
                'verbose_name_plural': '과목',
            },
        ),
        migrations.AlterModelOptions(
            name='problemtestcase',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='points',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='point value'),
        ),
        migrations.AddField(
            model_name='contest',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.subject'),
        ),
    ]
