# Generated by Django 3.2.25 on 2024-08-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_auto_20240827_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtestcase',
            name='is_pretest',
            field=models.BooleanField(default=False, verbose_name='case is pretest?'),
        ),
    ]
