# Generated by Django 3.2.25 on 2024-08-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_alter_problemtestcase_is_pretest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='problem group ID'),
        ),
    ]
