# Generated by Django 3.2.25 on 2025-02-27 17:51

import django.core.validators
from django.db import migrations, models
import judge.models.problem


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_alter_problemgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='encrypted_description',
            field=models.TextField(blank=True, null=True, verbose_name='암호화된 내용'),
        ),
        migrations.AddField(
            model_name='problem',
            name='encryption_key_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='암호화 키 해시'),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='문제를 암호화할지 여부를 설정합니다.', verbose_name='암호화'),
        ),
        migrations.AlterField(
            model_name='languagelimit',
            name='memory_limit',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1048576000)], verbose_name='memory limit'),
        ),
        migrations.AlterField(
            model_name='languagelimit',
            name='time_limit',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60000)], verbose_name='time limit'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(default='본문 내용 작성\n                                    \n## 입력 설명\n입력 제한 설명\n\n## 출력 설명\n출력 제한 설명\n\n## 예제 입력\n```\n테스트케이스 예제 입력\n```\n\n## 예제 출력\n```\n테스트케이스 예제 출력\n```', null=True, validators=[judge.models.problem.disallowed_characters_validator], verbose_name='problem body'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.FloatField(default=2.0, help_text='The time limit for this problem, in seconds. Fractional seconds (e.g. 1.5) are supported.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60000)], verbose_name='time limit'),
        ),
        migrations.AlterField(
            model_name='problempointsvote',
            name='points',
            field=models.IntegerField(help_text='The amount of points the voter thinks this problem deserves.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)], verbose_name='proposed points'),
        ),
    ]
