# Generated by Django 3.2.25 on 2025-05-16 23:30

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_auto_20250227_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipation',
            name='problem_first_solved',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='first solve timestamps'),
        ),
    ]
