# Generated by Django 3.2.25 on 2025-07-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0011_alter_latestsubmission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsubmission',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.language', verbose_name='submission language'),
        ),
    ]
