# Generated by Django 3.2.25 on 2025-07-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0012_latestsubmission_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestsubmission',
            name='language',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='judge.language', verbose_name='submission language'),
        ),
    ]
