# Generated by Django 3.2.25 on 2025-07-31 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0014_auto_20250730_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemclarification',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem', verbose_name='clarified problem'),
        ),
    ]
