# Generated by Django 3.2.25 on 2025-07-31 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0015_alter_problemclarification_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemclarification',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='judge.problem', verbose_name='clarified problem'),
        ),
    ]
