# Generated by Django 3.2.25 on 2025-08-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0017_auto_20250817_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatchNoteCategory',
        ),
    ]
