# Generated by Django 3.2.25 on 2026-04-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0030_profile_site_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='site_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', '시스템 기본값')], default='light', max_length=5, verbose_name='site theme'),
        ),
    ]
